name: notemate
description: "An app for teachers and students to manage notes and announcements."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.12.0
  firebase_auth: ^5.5.0
  cloud_firestore: ^5.6.4
  firebase_storage: ^12.4.3
  url_launcher: ^6.3.1
  provider: ^6.1.2
  google_fonts: ^6.2.1
  file_picker: ^9.0.0
  fluttertoast: ^8.2.4
  flutter_spinkit: ^5.2.0
  chat_gpt_sdk: ^3.1.4
  http: ^1.3.0
  permission_handler: ^11.4.0
  lottie: ^3.2.0
  shared_preferences: ^2.2.2
  syncfusion_flutter_pdfviewer: ^28.1.37  # ✅ Compatible version
  flutter_plugin_android_lifecycle: ^2.0.25
  dio: ^5.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700