// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDlrr0LOjE0BcDgo5-AWZdJgW3VsIUIqI',
    appId: '1:264290447726:web:2f98b133d6be418b3f517f',
    messagingSenderId: '264290447726',
    projectId: 'notemate-66306',
    authDomain: 'notemate-66306.firebaseapp.com',
    storageBucket: 'notemate-66306.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRJd3pfVPkdYVdRQ729hLuoPJGvKZkwFQ',
    appId: '1:264290447726:android:4878579f00c7a39e3f517f',
    messagingSenderId: '264290447726',
    projectId: 'notemate-66306',
    storageBucket: 'notemate-66306.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7MNL1q9Sfuh1IAuICMUPy4Li4pNVISx0',
    appId: '1:264290447726:ios:5b906850de9ede3a3f517f',
    messagingSenderId: '264290447726',
    projectId: 'notemate-66306',
    storageBucket: 'notemate-66306.firebasestorage.app',
    iosBundleId: 'com.example.notemate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7MNL1q9Sfuh1IAuICMUPy4Li4pNVISx0',
    appId: '1:264290447726:ios:5b906850de9ede3a3f517f',
    messagingSenderId: '264290447726',
    projectId: 'notemate-66306',
    storageBucket: 'notemate-66306.firebasestorage.app',
    iosBundleId: 'com.example.notemate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDlrr0LOjE0BcDgo5-AWZdJgW3VsIUIqI',
    appId: '1:264290447726:web:728837b9d2a29b033f517f',
    messagingSenderId: '264290447726',
    projectId: 'notemate-66306',
    authDomain: 'notemate-66306.firebaseapp.com',
    storageBucket: 'notemate-66306.firebasestorage.app',
  );
}
